---
name: stratisd CI containerised

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'

  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          - task: make -f Makefile clippy
            toolchain: 1.63.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: clippy
          - task: make -f Makefile build
            toolchain: 1.63.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: make -f Makefile build-min
            toolchain: 1.63.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: make -f Makefile test
            toolchain: 1.63.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
    runs-on: ubuntu-18.04
    container:
      image: fedora:36  # CURRENT DEVELOPMENT ENVIRONMENT
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          cryptsetup-devel
          dbus-devel
          device-mapper-persistent-data
          device-mapper-devel
          libblkid-devel
          make
          systemd-devel
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}

  # TESTS WITH UDEV
  checks_with_udev:
    strategy:
      matrix:
        include:
          - task: RUST_LOG=trace make -f Makefile test-loop
            toolchain: 1.63.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
    runs-on: ubuntu-18.04
    steps:
      - run: |
          ps ax --forest
          whoami
          sudo killall systemd-udevd
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run the test process in container
        uses: addnab/docker-run-action@v3
        with:
          image: fedora:36
          options: --privileged -v /dev:/dev
          run: |
            dnf install -y asciidoc clang cryptsetup-devel curl dbus-devel device-mapper-devel device-mapper-persistent-data libblkid-devel make systemd-devel systemd-udev xfsprogs
            ps ax --forest
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          image: fedora:36
          options: --privileged -v /dev:/dev
          run: make -f Makefile install-release
      - name: Start udev
        with:
          image: fedora:36
          options: --privileged -v /dev:/dev
          run: /usr/lib/systemd/systemd-udevd &
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        with:
          image: fedora:36
          options: --privileged -v /dev:/dev
          run: ${{ matrix.task }}
