---
name: stratisd CI on fedora

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'

  workflow_dispatch:

jobs:
  # TESTS WITH UDEV
  checks_with_udev:
    runs-on: ubuntu-18.04
    container:
      image: fedora:36  # CURRENT DEVELOPMENT ENVIRONMENT
      options: --privileged -v /dev:/dev
    steps:
      - name: Checkout sources
      - uses: actions/checkout@v2
      - name: Stop host udevd
        run: sudo killall systemd-udevd
      - name: Run tests in container
      - uses: bmr-cymru/fedora-stratisd-composite-action@main
