---
name: stratisd CI on fedora

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-18.04
    name: Test Fedora Container Action
    steps:
      - name: s-f-c-a
        id: sfca
        uses: bmr-cymru/stratis-fedora-container-action@main
        with:
          options: --privileged -v /dev:/dev
