---
name: stratisd CI on fedora container

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-18.04
    name: Test Fedora Container Action
    steps:
      - name: s-f-c-a
        id: sfca
        uses: bmr-cymru/stratis-fedora-container-action@main
        with:
          run:
            dnf install -y asciidoc clang cryptsetup-devel curl dbus-devel device-mapper-devel device-mapper-persistent-data libblkid-devel make systemd-devel systemd-udev xfsprogs procps-ng
            cat /etc/os-release
            echo "Hello Stratis World!"
